/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VKClffZTeZh
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function Subscription() {
  return (
    <div className="flex flex-col h-screen bg-gray-100 dark:bg-gray-900">
      <header className="flex items-center justify-between px-6 py-4 bg-white dark:bg-gray-800 shadow">
        <h1 className="text-lg font-semibold">Billing</h1>
        <div className="flex items-center space-x-2">
          <span className="text-sm text-gray-800 dark:text-gray-200">John Doe</span>
          <Avatar className="h-8 w-8">
            <AvatarImage alt="John Doe" src="/placeholder-avatar.jpg" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
        </div>
      </header>
      <main className="flex-1 overflow-y-auto p-6">
        <Card className="mb-8">
          <CardHeader>
            <CardTitle>Current Plan</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col space-y-2">
            <div className="text-lg font-semibold">Pro Plan</div>
            <ul className="list-disc list-inside space-y-1 text-sm text-gray-600 dark:text-gray-400">
              <li>Unlimited projects</li>
              <li>Priority support</li>
              <li>Extra security features</li>
            </ul>
            <div className="text-lg font-semibold">$29/month</div>
          </CardContent>
          <CardFooter className="flex space-x-2">
            <Button variant="outline">Upgrade</Button>
            <Button variant="outline">Downgrade</Button>
            <Button className="ml-auto" variant="outline">
              Cancel Subscription
            </Button>
          </CardFooter>
        </Card>
        <Card className="mb-8">
          <CardHeader>
            <CardTitle>Billing History</CardTitle>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Date</TableHead>
                  <TableHead>Amount</TableHead>
                  <TableHead>Description</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell>01/01/2024</TableCell>
                  <TableCell>$29.00</TableCell>
                  <TableCell>Pro Plan - January 2024</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>12/01/2023</TableCell>
                  <TableCell>$29.00</TableCell>
                  <TableCell>Pro Plan - December 2023</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>11/01/2023</TableCell>
                  <TableCell>$29.00</TableCell>
                  <TableCell>Pro Plan - November 2023</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Payment Information</CardTitle>
          </CardHeader>
          <CardContent>
            <form className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="cardNumber">Card Number</Label>
                <Input id="cardNumber" type="text" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="expiryDate">Expiry Date</Label>
                <Input id="expiryDate" type="text" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="cvv">CVV</Label>
                <Input id="cvv" type="text" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="billingAddress">Billing Address</Label>
                <Input id="billingAddress" type="text" />
              </div>
              <Button className="w-full" type="submit">
                Update Payment Information
              </Button>
            </form>
          </CardContent>
        </Card>
      </main>
    </div>
  )
}
