/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3quibfsjCnv
 */
import {Button} from 'components/ui/button';
import {Title} from 'react-head';
import {useNavigate} from 'react-router';
import {NavLink, useRouteError} from 'react-router-dom';

interface IMessagePageProps {
    code?: number;
    message: string;
    description: string;
}

export function MessagePage(props: IMessagePageProps) {
    const navigate = useNavigate();

    const error = useRouteError() as Error & { status: number, statusText: string };
    const code = props.code || error?.status || 500;
    const message = props.message || error?.statusText || 'Error';
    const description = props.description || 'Oops! Something went wrong.';

    return (
        <>
            <Title>{message}</Title>
            <div className="mx-auto max-w-md space-y-6">
                <div className="space-y-2 text-center">
                    {code && <h1 className="text-3xl font-bold">{code}</h1>}
                    <h2 className="text-2xl font-medium">{message}</h2>
                    <p className="text-gray-500 dark:text-gray-400">{description}</p>
                </div>
                <div className="space-y-4">
                    <Button className="w-full" onClick={() => navigate('/')}>
                        Go to Home
                    </Button>
                </div>
                <div className="mt-4 text-center text-sm">
                    Need help? &nbsp;
                    <NavLink className="underline" to="/contact">
                        Contact Support
                    </NavLink>
                </div>
            </div>
        </>
    );
}
