/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3quibfsjCnv
 */
import { Button } from "components/ui/button"
import {NavLink} from 'react-router-dom';

interface IMessagePageProps {
    code?: number;
    message: string;
    description: string;
}

export function MessagePage(props: IMessagePageProps) {
  return (
    <div className="mx-auto max-w-md space-y-6">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">{props.code} {props.message}</h1>
        <p className="text-gray-500 dark:text-gray-400">{props.description}</p>
      </div>
      <div className="space-y-4">
        <Button className="w-full" type="submit">
          Go to Home
        </Button>
      </div>
      <div className="mt-4 text-center text-sm">
        Need help?
        <NavLink className="underline" to="#">
          Contact Support
        </NavLink>
      </div>
    </div>
  )
}
