/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0LbfMctIUTC
 */
import { Button } from "components/ui/button"
import {NavLink} from 'react-router-dom';

export function AccountActivated() {
  return (
    <div className="mx-auto max-w-md space-y-6">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Account Activated</h1>
        <p className="text-gray-500 dark:text-gray-400">Your account has been successfully activated!</p>
      </div>
      <div className="space-y-4">
        <Button className="w-full" type="submit">
          Go to Dashboard
        </Button>
      </div>
      <div className="mt-4 text-center text-sm">
        Need help?
        <NavLink className="underline" to="#">
          Contact Support
        </NavLink>
      </div>
    </div>
  )
}
