name: Test
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Enable corepack
        run: corepack enable

      - name: Install Dependencies
        run: yarn install

      - name: Run Lint
        run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Enable corepack
        run: corepack enable

      - name: Install Dependencies
        run: yarn install

      - name: Jest Unit Test
        run: yarn test:coverage

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        id: coverageComment
        with:
          coverage-summary-path: ./coverage/coverage-summary.json
          title: Unit Test Coverage
          summary-title: Coverage Summary
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          coverage-title: Coverage
          coverage-path: ./coverage/coverage.txt

      - name: Check the output coverage
        run: |
          echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
          echo "Summary HTML - ${{ steps.coverageComment.outputs.summaryHtml }}"

      - name: Create the badge
        if: github.ref == 'refs/heads/master'
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.JEST_COVERAGE_COMMENT }}
          gistID: b0f8fef776a5c6e55b3787a23e456421
          filename: shortx-ui-coverage.json
          label: Coverage
          message: ${{ steps.coverageComment.outputs.coverage }}%
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: typescript
