name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: Install Dependencies
        run: yarn install
      - name: Jest Unit Test
        run: yarn test:unit --no-cache
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
